<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>swift</string>
	</array>
	<key>name</key>
	<string>SWIFT</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(\:\w{1,3}\:)</string>
			<key>name</key>
			<string>entity.name.tag</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?!\:)(\/\w{1,6}\/)</string>
			<key>name</key>
			<string>storage.type.tag</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?!\:\w{1,3}\:)([\w,\s]*)\n</string>
			<key>name</key>
			<string>variable</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.swift</string>
	<key>uuid</key>
	<string>7fa23102-c5ad-4d1a-a1d5-0cf6ad83dc43</string>
</dict>
</plist>
